### ISSUE TITLE
InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.

### ISSUE THREAD

**Issue by gogoge** [adrianhall/restaurant-reviews#3]
hi Adrian, 

Thaks for your useful tutorial,
I got the error msg in title these days, and finally fix it.
I don't know why other people never face this problem.
So I post my solution, if this is not the root cause, I hope someone can correct me.

Here is my solution:

https://github.com/adrianhall/restaurant-reviews/blob/p2/backend/serverless.yml#L98
https://github.com/adrianhall/restaurant-reviews/blob/p2/backend/serverless.yml#L113

modify "cognito-identity.`amazon`.com:amr" to "cognito-identity.`amazonaws`.com:amr"

**Comment by adrianhall** [comment]
THanks for the update.  This has already been done in the master branch.
