### ISSUE TITLE
[Question]: How to handle image upload in offline mode

### ISSUE THREAD

**Issue by jhanitesh10** [adrianhall/restaurant-reviews#5]
Describe the question
Hi Adrianhall,

I am following your tutorials and you are amazing. I need your to view on my problem If you get time to look into my question and make comment on it.

I following your tutorial and using AppSync, S3 for image upload. Looking for how to handle the image upload in offline mode.

Expected behavior
When the user is an offline mode uploads images. I want to show image in offline mode itself and upload an image into s3 as soon as he comes online.

StackOverflow Url
https://stackoverflow.com/questions/56374422/handle-offline-image-upload-using-appsync-and-s3

Thanks,

**Comment by adrianhall** [comment]
I am no longer working on AWS stuff.  Suggest you reach out to @dabit3
